DOMAIN="ukraine-api-gateway-624ct11y.ew.gateway.dev"

echo "ADMIN"
echo "https://${DOMAIN}/admin-add-tweet?username=renato&password=password&tweetusername=renato_username&tweettext=renato_tweettext"
echo "https://${DOMAIN}/admin-add-tweet?username=user&password=pass&tweetusername=renato_username&tweettext=renato_tweettext"
echo "https://${DOMAIN}/admin-delete-tweet?username=renato&password=password&tweetid="
echo "https://${DOMAIN}/admin-delete-tweet?username=user&password=pass&tweetid="
echo "LIST"
echo "https://${DOMAIN}/list-tweet-language?language=en"
echo "https://${DOMAIN}/list-tweet-language?language=en&limit=2"
echo "https://${DOMAIN}/list-tweet-location?location=us"
echo "https://${DOMAIN}/list-tweet-location?location=us&limit=3"
echo "https://${DOMAIN}/list-tweet-random"
echo "https://${DOMAIN}/list-tweet-search?search=ukraine"
echo "https://${DOMAIN}/list-tweet-search?search=ukraine&limit=4"
echo "https://${DOMAIN}/list-tweet-username?username=BARRAL42604501"
echo "https://${DOMAIN}/list-tweet-username?username=BARRAL42604501&limit=4"
