apiVersion: v1
kind: Service
metadata:
  name: search-svc
spec:
  selector:
    app: search
    version: one
  ports:
  - protocol: TCP
    port: 60200
    targetPort: 60200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment-v1
spec:
  selector:
    matchLabels:
      app: search
      version: one
  replicas: 3
  template:
    metadata:
      labels:
        app: search
        version: one
    spec:
      containers:
      - name: search
        image: "europe-west1-docker.pkg.dev/cadeira-nuvem-2122/cloud-microservices/searchflask:latest"
        env:
            - name: STRING_HOST
              valueFrom:
                configMapKeyRef:
                  name: search-configmap
                  key: string_service_name
            - name: USERNAME_HOST
              valueFrom:
                configMapKeyRef:
                  name: search-configmap
                  key: username_service_name
---
apiVersion: v1
kind: Service
metadata:
  name: search-string-svc
spec:
  selector:
    app: search-string
    version: one
  ports:
  - protocol: TCP
    port: 60210
    targetPort: 60210
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-string-deployment-v1
spec:
  selector:
    matchLabels:
      app: search-string
      version: one
  replicas: 3
  template:
    metadata:
      labels:
        app: search-string
        version: one
    spec:
      volumes:
      - name: bq-read-key
        secret:
          secretName: bq-key
      containers:
      - name: search-string
        image: "europe-west1-docker.pkg.dev/cadeira-nuvem-2122/cloud-microservices/searchstring:latest"
        volumeMounts:
        - name: bq-read-key
          mountPath: /var/secrets/bq
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/bq/key.json
---
apiVersion: v1
kind: Service
metadata:
  name: search-username-svc
spec:
  selector:
    app: search-username
    version: one
  ports:
  - protocol: TCP
    port: 60220
    targetPort: 60220
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-username-deployment-v1
spec:
  selector:
    matchLabels:
      app: search-username
      version: one
  replicas: 3
  template:
    metadata:
      labels:
        app: search-username
        version: one
    spec:
      volumes:
      - name: bq-read-key
        secret:
          secretName: bq-key
      containers:
      - name: search-username
        image: "europe-west1-docker.pkg.dev/cadeira-nuvem-2122/cloud-microservices/searchusername:latest"
        volumeMounts:
        - name: bq-read-key
          mountPath: /var/secrets/bq
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/bq/key.json