# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clear_tweet_proto_pb2 as clear__tweet__proto__pb2


class ClearTweetsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClearTweet = channel.unary_unary(
                '/ClearTweets/ClearTweet',
                request_serializer=clear__tweet__proto__pb2.ClearListRequest.SerializeToString,
                response_deserializer=clear__tweet__proto__pb2.ClearListResponse.FromString,
                )


class ClearTweetsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClearTweet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClearTweetsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClearTweet': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearTweet,
                    request_deserializer=clear__tweet__proto__pb2.ClearListRequest.FromString,
                    response_serializer=clear__tweet__proto__pb2.ClearListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClearTweets', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClearTweets(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClearTweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClearTweets/ClearTweet',
            clear__tweet__proto__pb2.ClearListRequest.SerializeToString,
            clear__tweet__proto__pb2.ClearListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
