# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tweetMessages_pb2 as tweetMessages__pb2


class BD_LocationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RetrieveLocations = channel.unary_unary(
                '/BD_Locations/RetrieveLocations',
                request_serializer=tweetMessages__pb2.TimeIntervalRequest.SerializeToString,
                response_deserializer=tweetMessages__pb2.listLocationResponse.FromString,
                )


class BD_LocationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RetrieveLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BD_LocationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RetrieveLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveLocations,
                    request_deserializer=tweetMessages__pb2.TimeIntervalRequest.FromString,
                    response_serializer=tweetMessages__pb2.listLocationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BD_Locations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BD_Locations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RetrieveLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BD_Locations/RetrieveLocations',
            tweetMessages__pb2.TimeIntervalRequest.SerializeToString,
            tweetMessages__pb2.listLocationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ServiceLocationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LocationsCleaner = channel.unary_unary(
                '/ServiceLocations/LocationsCleaner',
                request_serializer=tweetMessages__pb2.TimeIntervalRequest.SerializeToString,
                response_deserializer=tweetMessages__pb2.listLocationResponse.FromString,
                )


class ServiceLocationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LocationsCleaner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceLocationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LocationsCleaner': grpc.unary_unary_rpc_method_handler(
                    servicer.LocationsCleaner,
                    request_deserializer=tweetMessages__pb2.TimeIntervalRequest.FromString,
                    response_serializer=tweetMessages__pb2.listLocationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServiceLocations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServiceLocations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LocationsCleaner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServiceLocations/LocationsCleaner',
            tweetMessages__pb2.TimeIntervalRequest.SerializeToString,
            tweetMessages__pb2.listLocationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
