# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproto.proto\"K\n\x05Tweet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\x04text\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04user\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_textB\x07\n\x05_user\".\n\x10\x43learListRequest\x12\x1a\n\ntweet_list\x18\x01 \x03(\x0b\x32\x06.Tweet\"/\n\x11\x43learListResponse\x12\x1a\n\ntweet_list\x18\x01 \x03(\x0b\x32\x06.Tweet2B\n\x0b\x43learTweets\x12\x33\n\nClearTweet\x12\x11.ClearListRequest\x1a\x12.ClearListResponseb\x06proto3')



_TWEET = DESCRIPTOR.message_types_by_name['Tweet']
_CLEARLISTREQUEST = DESCRIPTOR.message_types_by_name['ClearListRequest']
_CLEARLISTRESPONSE = DESCRIPTOR.message_types_by_name['ClearListResponse']
Tweet = _reflection.GeneratedProtocolMessageType('Tweet', (_message.Message,), {
  'DESCRIPTOR' : _TWEET,
  '__module__' : 'proto_pb2'
  # @@protoc_insertion_point(class_scope:Tweet)
  })
_sym_db.RegisterMessage(Tweet)

ClearListRequest = _reflection.GeneratedProtocolMessageType('ClearListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLEARLISTREQUEST,
  '__module__' : 'proto_pb2'
  # @@protoc_insertion_point(class_scope:ClearListRequest)
  })
_sym_db.RegisterMessage(ClearListRequest)

ClearListResponse = _reflection.GeneratedProtocolMessageType('ClearListResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLEARLISTRESPONSE,
  '__module__' : 'proto_pb2'
  # @@protoc_insertion_point(class_scope:ClearListResponse)
  })
_sym_db.RegisterMessage(ClearListResponse)

_CLEARTWEETS = DESCRIPTOR.services_by_name['ClearTweets']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TWEET._serialized_start=15
  _TWEET._serialized_end=90
  _CLEARLISTREQUEST._serialized_start=92
  _CLEARLISTREQUEST._serialized_end=138
  _CLEARLISTRESPONSE._serialized_start=140
  _CLEARLISTRESPONSE._serialized_end=187
  _CLEARTWEETS._serialized_start=189
  _CLEARTWEETS._serialized_end=255
# @@protoc_insertion_point(module_scope)
