steps:
  ## admin_add_tweets pipeline
  - name: '${_LOCATION}-docker.pkg.dev/${_PROJECT}/utils/zip-utils'
    args: ['-j', 'admin_add_tweet.zip', 
          'serverless/functions/admin_add_tweet/app/main.py',
          'serverless/functions/admin_add_tweet/requirements.txt',]
    id: 'zip-admin-add-tweet'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'admin_add_tweet.zip', 'gs://tweets-cloudfunctions-zip']
    id: 'add-to-storage-admin-add-tweet'
    waitFor: ['zip-admin-add-tweet']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 
            'admin-add-tweet',
            '--region=europe-west1',
            '--runtime=python38',
            '--entry-point=main',
            '--trigger-http',
            '--source=gs://tweets-cloudfunctions-zip/admin_add_tweet.zip',
            '--env-vars-file=serverless/functions/.env-admin.yaml']
    id: 'deploy-admin-add-tweet'
    waitFor: ['add-to-storage-admin-add-tweet']

    ## admin_delete_tweets pipeline
  - name: '${_LOCATION}-docker.pkg.dev/${_PROJECT}/utils/zip-utils'
    args: ['-j', 'admin_delete_tweet.zip', 
          'serverless/functions/admin_delete_tweet/app/main.py',
          'serverless/functions/admin_delete_tweet/requirements.txt',]
    id: 'zip-admin-delete-tweet'
    waitFor: ['deploy-admin-add-tweet']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'admin_delete_tweet.zip', 'gs://tweets-cloudfunctions-zip']
    id: 'add-to-storage-admin-delete-tweet'
    waitFor: ['zip-admin-delete-tweet']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 
            'admin-delete-tweet',
            '--region=europe-west1',
            '--runtime=python38',
            '--entry-point=main',
            '--trigger-http',
            '--source=gs://tweets-cloudfunctions-zip/admin_delete_tweet.zip',
            '--env-vars-file=serverless/functions/.env-admin.yaml']
    id: 'deploy-admin-delete-tweet'
    waitFor: ['zip-admin-delete-tweet']

    ## auth pipeline
  - name: '${_LOCATION}-docker.pkg.dev/${_PROJECT}/utils/zip-utils'
    args: ['-j', 'auth.zip', 
          'serverless/functions/auth/app/main.py',
          'serverless/functions/auth/requirements.txt',]
    id: 'zip-auth'
    waitFor: ['deploy-admin-delete-tweet']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'auth.zip', 'gs://tweets-cloudfunctions-zip']
    id: 'add-to-storage-auth'
    waitFor: ['zip-auth']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 
            'auth',
            '--region=europe-west1',
            '--runtime=python38',
            '--entry-point=main',
            '--trigger-http',
            '--source=gs://tweets-cloudfunctions-zip/auth.zip',
            '--env-vars-file=serverless/functions/.env-admin.yaml']
    id: 'deploy-auth'
    waitFor: ['add-to-storage-auth']

    ## clear_tweet_list pipeline
  - name: '${_LOCATION}-docker.pkg.dev/${_PROJECT}/utils/zip-utils'
    args: ['-j', 'clear_tweet_list.zip', 
          'serverless/functions/clear_tweet_list/app/main.py',
          'serverless/functions/clear_tweet_list/requirements.txt',]
    id: 'zip-clear_tweet_list'
    waitFor: ['deploy-auth']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'clear_tweet_list.zip', 'gs://tweets-cloudfunctions-zip']
    id: 'add-to-storage-clear_tweet_list'
    waitFor: ['zip-clear_tweet_list']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 
            'clear_tweet_list',
            '--region=europe-west1',
            '--runtime=python38',
            '--entry-point=main',
            '--trigger-http',
            '--source=gs://tweets-cloudfunctions-zip/clear_tweet_list.zip',
            '--env-vars-file=serverless/functions/.env-admin.yaml']
    id: 'deploy-clear_tweet_list'
    waitFor: ['add-to-storage-clear_tweet_list']

    ## list_tweet_language pipeline
  - name: '${_LOCATION}-docker.pkg.dev/${_PROJECT}/utils/zip-utils'
    args: ['-j', 'list_tweet_language.zip', 
          'serverless/functions/list_tweet_language/app/main.py',
          'serverless/functions/list_tweet_language/requirements.txt',]
    id: 'zip-list_tweet_language'
    waitFor: ['deploy-clear_tweet_list']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'list_tweet_language.zip', 'gs://tweets-cloudfunctions-zip']
    id: 'add-to-storage-list_tweet_language'
    waitFor: ['zip-list_tweet_language']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 
            'list_tweet_language',
            '--region=europe-west1',
            '--runtime=python38',
            '--entry-point=main',
            '--trigger-http',
            '--source=gs://tweets-cloudfunctions-zip/list_tweet_language.zip',
            '--env-vars-file=serverless/functions/.env-admin.yaml']
    id: 'deploy-list_tweet_language'
    waitFor: ['add-to-storage-list_tweet_language']

    ## list_tweet_location pipeline
  - name: '${_LOCATION}-docker.pkg.dev/${_PROJECT}/utils/zip-utils'
    args: ['-j', 'list_tweet_location.zip', 
          'serverless/functions/list_tweet_location/app/main.py',
          'serverless/functions/list_tweet_location/requirements.txt',]
    id: 'zip-list_tweet_location'
    waitFor: ['deploy-list_tweet_language']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'list_tweet_location.zip', 'gs://tweets-cloudfunctions-zip']
    id: 'add-to-storage-list_tweet_location'
    waitFor: ['zip-list_tweet_location']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 
            'list_tweet_location',
            '--region=europe-west1',
            '--runtime=python38',
            '--entry-point=main',
            '--trigger-http',
            '--source=gs://tweets-cloudfunctions-zip/list_tweet_location.zip',
            '--env-vars-file=serverless/functions/.env-admin.yaml']
    id: 'deploy-list_tweet_location'
    waitFor: ['add-to-storage-list_tweet_location']

    ## list_tweet_random pipeline
  - name: '${_LOCATION}-docker.pkg.dev/${_PROJECT}/utils/zip-utils'
    args: ['-j', 'list_tweet_random.zip', 
          'serverless/functions/list_tweet_random/app/main.py',
          'serverless/functions/list_tweet_random/requirements.txt',]
    id: 'zip-list_tweet_random'
    waitFor: ['deploy-list_tweet_location']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'list_tweet_random.zip', 'gs://tweets-cloudfunctions-zip']
    id: 'add-to-storage-list_tweet_random'
    waitFor: ['zip-list_tweet_random']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 
            'list_tweet_random',
            '--allow-unauthenticated',
            '--region=europe-west1',
            '--runtime=python38',
            '--entry-point=main',
            '--trigger-http',
            '--source=gs://tweets-cloudfunctions-zip/list_tweet_random.zip',
            '--env-vars-file=serverless/functions/.env-admin.yaml']
    id: 'deploy-list_tweet_random'
    waitFor: ['add-to-storage-list_tweet_random']

    ## list_tweet_search pipeline
  - name: '${_LOCATION}-docker.pkg.dev/${_PROJECT}/utils/zip-utils'
    args: ['-j', 'list_tweet_search.zip', 
          'serverless/functions/list_tweet_search/app/main.py',
          'serverless/functions/list_tweet_search/requirements.txt',]
    id: 'zip-list_tweet_search'
    waitFor: ['deploy-list_tweet_random']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'list_tweet_search.zip', 'gs://tweets-cloudfunctions-zip']
    id: 'add-to-storage-list_tweet_search'
    waitFor: ['zip-list_tweet_search']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 
            'list_tweet_search',
            '--allow-unauthenticated',
            '--region=europe-west1',
            '--runtime=python38',
            '--entry-point=main',
            '--trigger-http',
            '--source=gs://tweets-cloudfunctions-zip/list_tweet_search.zip',
            '--env-vars-file=serverless/functions/.env-admin.yaml']
    id: 'deploy-list_tweet_search'
    waitFor: ['add-to-storage-list_tweet_search']

    ## list_tweet_username pipeline
  - name: '${_LOCATION}-docker.pkg.dev/${_PROJECT}/utils/zip-utils'
    args: ['-j', 'list_tweet_username.zip', 
          'serverless/functions/list_tweet_username/app/main.py',
          'serverless/functions/list_tweet_username/requirements.txt',]
    id: 'zip-list_tweet_username'
    waitFor: ['deploy-list_tweet_search']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'list_tweet_username.zip', 'gs://tweets-cloudfunctions-zip']
    id: 'add-to-storage-list_tweet_username'
    waitFor: ['zip-list_tweet_username']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 
            'list_tweet_username',
            '--allow-unauthenticated',
            '--region=europe-west1',
            '--runtime=python38',
            '--entry-point=main',
            '--trigger-http',
            '--source=gs://tweets-cloudfunctions-zip/list_tweet_username.zip',
            '--env-vars-file=serverless/functions/.env-admin.yaml']
    id: 'deploy-list_tweet_username'
    waitFor: ['add-to-storage-list_tweet_username']

tags: ['functions','deploy']