steps:
  ## admin_add_tweets pipeline
  - name: '${_LOCATION}-docker.pkg.dev/${_PROJECT}/utils/zip-utils'
    args: ['-j', 'admin_add_tweet.zip', 
          'serverless/functions/admin_add_tweet/app/main.py',
          'serverless/functions/admin_add_tweet/requirements.txt',]
    id: 'zip-admin-add-tweet'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'admin_add_tweet.zip', 'gs://tweets-cloudfunctions-zip']
    id: 'add-to-storage-admin-add-tweet'
    waitFor: ['zip-admin-add-tweet']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 
            'admin-add-tweet',
            '--region=europe-west1',
            '--runtime=python38',
            '--entry-point=main',
            '--trigger-http',
            '--source=gs://tweets-cloudfunctions-zip/admin_add_tweet.zip',
            '--env-vars-file=serverless/functions/.env-admin.yaml']
    id: 'deploy-admin-add-tweet'
    waitFor: ['zip-admin-add-tweet']

    ## admin_delete_tweets pipeline
  - name: '${_LOCATION}-docker.pkg.dev/${_PROJECT}/utils/zip-utils'
    args: ['-j', 'admin_delete_tweet.zip', 
          'serverless/functions/admin_delete_tweet/app/main.py',
          'serverless/functions/admin_delete_tweet/requirements.txt',]
    id: 'zip-admin-delete-tweet'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'admin_delete_tweet.zip', 'gs://tweets-cloudfunctions-zip']
    id: 'add-to-storage-admin-delete-tweet'
    waitFor: ['zip-admin-delete-tweet']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 
            'admin-delete-tweet',
            '--region=europe-west1',
            '--runtime=python38',
            '--entry-point=main',
            '--trigger-http',
            '--source=gs://tweets-cloudfunctions-zip/admin_delete_tweet.zip',
            '--env-vars-file=serverless/functions/.env-admin.yaml']
    id: 'deploy-admin-delete-tweet'
    waitFor: ['zip-admin-delete-tweet']

    ## auth pipeline
  - name: '${_LOCATION}-docker.pkg.dev/${_PROJECT}/utils/zip-utils'
    args: ['-j', 'auth.zip', 
          'serverless/functions/auth/app/main.py',
          'serverless/functions/auth/requirements.txt',]
    id: 'zip-auth'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'auth.zip', 'gs://tweets-cloudfunctions-zip']
    id: 'add-to-storage-auth'
    waitFor: ['zip-auth']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 
            'auth',
            '--region=europe-west1',
            '--runtime=python38',
            '--entry-point=main',
            '--trigger-http',
            '--source=gs://tweets-cloudfunctions-zip/auth.zip',
            '--env-vars-file=serverless/functions/.env-admin.yaml']
    id: 'deploy-auth'
    waitFor: ['zip-auth']

tags: ['functions','deploy']