steps:
- name: '${_LOCATION}-docker.pkg.dev/${_PROJECT}/utils/zip-utils'
  args: ['admin_add_tweet.zip', 
         'serverless/functions/admin_add_tweet/app/main.py',
         'serverless/functions/admin_add_tweet/requirements.txt',]
  id: 'zip-admin-add-tweet'
  waitFor: ['-']