apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: 23.251.133.28.nip.io
    http:
      paths:
      - path: /admin-add-tweet/
        pathType: Prefix
        backend:
          service:
            ## Service manifest in the random service folder
            name: admin-add-tweet
            port:
              number: 50051
      - path: /admin-delete-tweet/
        pathType: Prefix
        backend:
          service:
            ## Service manifest in the random service folder
            name: admin-delete-tweet
            port:
              number: 50052