apiVersion: v1
kind: Service
metadata:
  name: admin-add-tweet
spec:
  selector:
    app: admin-add-tweet
    version: one
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-add-tweet-deployment-v1
spec:
  selector:
    matchLabels:
      app: admin-add-tweet
      version: one
  replicas: 3
  template:
    metadata:
      labels:
        app: admin-add-tweet
        version: one
    spec:
      containers:
      - name: admin-add-tweet
        image: "europe-west1-docker.pkg.dev/cadeira-nuvem-2122/cloud-microservices/admin-add-tweet:latest"
        volumeMounts:
        - name: access-key
          mountPath: /home/bosutike/Cloud-Tweets-2122/services/keys
        env:
        - name: GOOGLE_ACCOUNT_KEY_PATH
          value: /home/bosutike/Cloud-Tweets-2122/services/keys/pythonBigQuery_credentials.json
---
apiVersion: v1
kind: Service
metadata:
  name: admin-delete-tweet
spec:
  selector:
    app: admin-delete-tweet
    version: one
  ports:
  - protocol: TCP
    port: 50052
    targetPort: 50052
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-delete-tweet-deployment-v1
spec:
  selector:
    matchLabels:
      app: admin-delete-tweet
      version: one
  replicas: 3
  template:
    metadata:
      labels:
        app: admin-delete-tweet
        version: one
    spec:
      containers:
      - name: admin-delete-tweet
        image: "europe-west1-docker.pkg.dev/cadeira-nuvem-2122/services/admin-delete-tweet:latest"
        volumeMounts:
        - name: access-key
          mountPath: /home/bosutike/Cloud-Tweets-2122/services/keys
        env:
        - name: GOOGLE_ACCOUNT_KEY_PATH
          value: /home/bosutike/Cloud-Tweets-2122/services/keys/pythonBigQuery_credentials.json
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
    version: one
  ports:
  - protocol: TCP
    port: 50000
    targetPort: 50000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment-v1
spec:
  selector:
    matchLabels:
      app: auth
      version: one
  replicas: 3
  template:
    metadata:
      labels:
        app: auth
        version: one
    spec:
      containers:
      - name: auth
        image: "europe-west1-docker.pkg.dev/cadeira-nuvem-2122/services/auth:latest"
--