apiVersion: v1
kind: Service
metadata:
  name: list-tweet-search
spec:
  selector:
    app: list-tweet
    version: one
  ports:
  - protocol: TCP
    port: 50084
    targetPort: 50084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: list-tweet-search-deployment-v1
spec:
  selector:
    matchLabels:
      app: list-tweet
      version: one
  replicas: 3
  template:
    metadata:
      labels:
        app: list-tweet
        version: one
    spec:
      containers:
      - name: list-tweet
        image: "europe-west4-docker.pkg.dev/cadeira-nuvem-2122/services/list-tweet-search:latest"
        volumeMounts:
        - name: bigquery-key
          mountPath: /var/secrets/bigquery
        env:
        - name: GOOGLE_ACCOUNT_KEY
          value: /var/secrets/bigquery/pythonBigQuery_credentials.json
        - name: CLEAR_TWEET_LIST_HOST
          value: clear-tweet-list
      volumes:
        - name: bigquery-key
          secret:
            secretName: bigquery-key
---
apiVersion: v1
kind: Service
metadata:
  name: clear-tweet-list
spec:
  selector:
    app: clear-tweet
    version: one
  ports:
  - protocol: TCP
    port: 50060
    targetPort: 50060
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clear-tweet-list-deployment-v1
spec:
  selector:
    matchLabels:
      app: clear-tweet
      version: one
  replicas: 3
  template:
    metadata:
      labels:
        app: clear-tweet
        version: one
    spec:
      containers:
      - name: clear-tweet
        image: "europe-west4-docker.pkg.dev/cadeira-nuvem-2122/services/clear-tweet-list:latest"
        volumeMounts:
        - name: bigquery-key
          mountPath: /var/secrets/bigquery
        env:
        - name: GOOGLE_ACCOUNT_KEY
          value: /var/secrets/bigquery/pythonBigQuery_credentials.json
      volumes:
        - name: bigquery-key
          secret:
            secretName: bigquery-key