# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tweetMessages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13tweetMessages.proto\"A\n\x13SearchStringRequest\x12\x14\n\x0csearchString\x18\x01 \x01(\t\x12\x14\n\x0climitResults\x18\x02 \x01(\x05\"A\n\x11SearchUserRequest\x12\x16\n\x0esearchUsername\x18\x01 \x01(\t\x12\x14\n\x0climitResults\x18\x02 \x01(\x05\"g\n\rResponseTweet\x12\x10\n\x08tweet_id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x13\n\x0bposted_time\x18\x04 \x01(\t\x12\x10\n\x08language\x18\x05 \x01(\t\"7\n\x12listTweetsResponse\x12!\n\tlistTweet\x18\x01 \x03(\x0b\x32\x0e.ResponseTweetb\x06proto3')



_SEARCHSTRINGREQUEST = DESCRIPTOR.message_types_by_name['SearchStringRequest']
_SEARCHUSERREQUEST = DESCRIPTOR.message_types_by_name['SearchUserRequest']
_RESPONSETWEET = DESCRIPTOR.message_types_by_name['ResponseTweet']
_LISTTWEETSRESPONSE = DESCRIPTOR.message_types_by_name['listTweetsResponse']
SearchStringRequest = _reflection.GeneratedProtocolMessageType('SearchStringRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHSTRINGREQUEST,
  '__module__' : 'tweetMessages_pb2'
  # @@protoc_insertion_point(class_scope:SearchStringRequest)
  })
_sym_db.RegisterMessage(SearchStringRequest)

SearchUserRequest = _reflection.GeneratedProtocolMessageType('SearchUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHUSERREQUEST,
  '__module__' : 'tweetMessages_pb2'
  # @@protoc_insertion_point(class_scope:SearchUserRequest)
  })
_sym_db.RegisterMessage(SearchUserRequest)

ResponseTweet = _reflection.GeneratedProtocolMessageType('ResponseTweet', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSETWEET,
  '__module__' : 'tweetMessages_pb2'
  # @@protoc_insertion_point(class_scope:ResponseTweet)
  })
_sym_db.RegisterMessage(ResponseTweet)

listTweetsResponse = _reflection.GeneratedProtocolMessageType('listTweetsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTTWEETSRESPONSE,
  '__module__' : 'tweetMessages_pb2'
  # @@protoc_insertion_point(class_scope:listTweetsResponse)
  })
_sym_db.RegisterMessage(listTweetsResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEARCHSTRINGREQUEST._serialized_start=23
  _SEARCHSTRINGREQUEST._serialized_end=88
  _SEARCHUSERREQUEST._serialized_start=90
  _SEARCHUSERREQUEST._serialized_end=155
  _RESPONSETWEET._serialized_start=157
  _RESPONSETWEET._serialized_end=260
  _LISTTWEETSRESPONSE._serialized_start=262
  _LISTTWEETSRESPONSE._serialized_end=317
# @@protoc_insertion_point(module_scope)
