# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tweetMessages_pb2 as tweetMessages__pb2


class RandomTimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReturnRandomTime = channel.unary_unary(
                '/RandomTime/ReturnRandomTime',
                request_serializer=tweetMessages__pb2.RandomTimeIntervalRequest.SerializeToString,
                response_deserializer=tweetMessages__pb2.RandomResponse.FromString,
                )


class RandomTimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReturnRandomTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RandomTimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReturnRandomTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnRandomTime,
                    request_deserializer=tweetMessages__pb2.RandomTimeIntervalRequest.FromString,
                    response_serializer=tweetMessages__pb2.RandomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RandomTime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RandomTime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReturnRandomTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RandomTime/ReturnRandomTime',
            tweetMessages__pb2.RandomTimeIntervalRequest.SerializeToString,
            tweetMessages__pb2.RandomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
