# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tweetMessages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13tweetMessages.proto\"!\n\x11RandomLangRequest\x12\x0c\n\x04lang\x18\x01 \x01(\t\"?\n\x19RandomTimeIntervalRequest\x12\x11\n\tstartTime\x18\x01 \x01(\t\x12\x0f\n\x07\x65ndTime\x18\x02 \x01(\t\"h\n\x0eRandomResponse\x12\x10\n\x08tweet_id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x13\n\x0bposted_time\x18\x04 \x01(\t\x12\x10\n\x08language\x18\x05 \x01(\tb\x06proto3')



_RANDOMLANGREQUEST = DESCRIPTOR.message_types_by_name['RandomLangRequest']
_RANDOMTIMEINTERVALREQUEST = DESCRIPTOR.message_types_by_name['RandomTimeIntervalRequest']
_RANDOMRESPONSE = DESCRIPTOR.message_types_by_name['RandomResponse']
RandomLangRequest = _reflection.GeneratedProtocolMessageType('RandomLangRequest', (_message.Message,), {
  'DESCRIPTOR' : _RANDOMLANGREQUEST,
  '__module__' : 'tweetMessages_pb2'
  # @@protoc_insertion_point(class_scope:RandomLangRequest)
  })
_sym_db.RegisterMessage(RandomLangRequest)

RandomTimeIntervalRequest = _reflection.GeneratedProtocolMessageType('RandomTimeIntervalRequest', (_message.Message,), {
  'DESCRIPTOR' : _RANDOMTIMEINTERVALREQUEST,
  '__module__' : 'tweetMessages_pb2'
  # @@protoc_insertion_point(class_scope:RandomTimeIntervalRequest)
  })
_sym_db.RegisterMessage(RandomTimeIntervalRequest)

RandomResponse = _reflection.GeneratedProtocolMessageType('RandomResponse', (_message.Message,), {
  'DESCRIPTOR' : _RANDOMRESPONSE,
  '__module__' : 'tweetMessages_pb2'
  # @@protoc_insertion_point(class_scope:RandomResponse)
  })
_sym_db.RegisterMessage(RandomResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RANDOMLANGREQUEST._serialized_start=23
  _RANDOMLANGREQUEST._serialized_end=56
  _RANDOMTIMEINTERVALREQUEST._serialized_start=58
  _RANDOMTIMEINTERVALREQUEST._serialized_end=121
  _RANDOMRESPONSE._serialized_start=123
  _RANDOMRESPONSE._serialized_end=227
# @@protoc_insertion_point(module_scope)
