steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/utils/python-utils', 'serverless/ci_cd/utils/.' ]

images: ['${LOCATION}-docker.pkg.dev/${PROJECT_ID}/utils/python-utils']

timeout: 3600s

substitutions:
  TRIGGER_NAME: name-replaced