# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61uth_proto.proto\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"/\n\x0c\x41uthResponse\x12\x1f\n\x08response\x18\x01 \x01(\x0e\x32\r.ResponseType*2\n\x0cResponseType\x12\x12\n\x0eNOT_AUTHORIZED\x10\x00\x12\x0e\n\nAUTHORIZED\x10\x01\x32=\n\x0e\x41uthentication\x12+\n\x0c\x41uthenticate\x12\x0c.AuthRequest\x1a\r.AuthResponseb\x06proto3')

_RESPONSETYPE = DESCRIPTOR.enum_types_by_name['ResponseType']
ResponseType = enum_type_wrapper.EnumTypeWrapper(_RESPONSETYPE)
NOT_AUTHORIZED = 0
AUTHORIZED = 1


_AUTHREQUEST = DESCRIPTOR.message_types_by_name['AuthRequest']
_AUTHRESPONSE = DESCRIPTOR.message_types_by_name['AuthResponse']
AuthRequest = _reflection.GeneratedProtocolMessageType('AuthRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTHREQUEST,
  '__module__' : 'auth_proto_pb2'
  # @@protoc_insertion_point(class_scope:AuthRequest)
  })
_sym_db.RegisterMessage(AuthRequest)

AuthResponse = _reflection.GeneratedProtocolMessageType('AuthResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTHRESPONSE,
  '__module__' : 'auth_proto_pb2'
  # @@protoc_insertion_point(class_scope:AuthResponse)
  })
_sym_db.RegisterMessage(AuthResponse)

_AUTHENTICATION = DESCRIPTOR.services_by_name['Authentication']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSETYPE._serialized_start=120
  _RESPONSETYPE._serialized_end=170
  _AUTHREQUEST._serialized_start=20
  _AUTHREQUEST._serialized_end=69
  _AUTHRESPONSE._serialized_start=71
  _AUTHRESPONSE._serialized_end=118
  _AUTHENTICATION._serialized_start=172
  _AUTHENTICATION._serialized_end=233
# @@protoc_insertion_point(module_scope)
