steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'builds',
      'submit',
      '--config=serverless/functions/ci_cd/unit_tests.cloudbuild.yaml',
      '--substitutions=_TRIGGER_NAME="cf-unittests",_LOCATION=${_LOCATION},_PROJECT=${_PROJECT}'
    ]
    id: 'unittests'
    waitFor: ['-']

substitutions:
  _PROJECT: ${PROJECT}
  _LOCATION: ${LOCATION}