steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'builds',
      'submit',
      '--config=serverless/functions/ci_cd/unit_tests.cloudbuild.yaml',
      '--substitutions=TRIGGER_NAME=${TRIGGER_NAME}'
    ]
    id: 'unittests'
    waitFor: ['-']