steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'builds',
      'submit',
      '--config=pulumi.cloudbuild.yaml',
      '--substitutions=_LOCATION=${_LOCATION},_PROJECT=${_PROJECT},_BUILD_TYPE=${_BUILD_TYPE}'
    ]
    id: 'pulumi'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'builds',
      'submit',
      '--config=serverless/functions/ci_cd/unit_tests.cloudbuild.yaml',
      '--substitutions=_LOCATION=${_LOCATION},_PROJECT=${_PROJECT}'
    ]
    id: 'unittests'
    waitFor: ['pulumi']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'builds',
      'submit',
      '--config=serverless/functions/ci_cd/deploy.cloudbuild.yaml',
      '--substitutions=_LOCATION=${_LOCATION},_PROJECT=${_PROJECT}'
    ]
    id: 'deploy-functions'
    waitFor: ['unittests']

substitutions:
  _PROJECT: tweets-cadeira-2122
  _LOCATION: europe-west1
  _BUILD_TYPE: up