steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - "TRIGGER_NAME=cf-unittests"
    args: [
      'builds',
      'submit',
      '--config=serverless/functions/ci_cd/unit_tests.cloudbuild.yaml',
    ]
    id: 'unittests'
    waitFor: ['-']